homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.6106
  longitude: 1.3347
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 185
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

influxdb:
    host: 127.0.0.1
    username: home-assistant
    password: password

sensor:
# Weather Prediction
  - platform: yr
    scan_interval: 120
  - platform: ha02
    i2c_port: 6
    scan_interval: 120
  - platform: grove_light
    port: 1
    scan_interval: 120
  - platform: systemmonitor
    scan_interval: 10
    resources:
      - type: disk_use_percent
        arg: /home
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use

device_tracker:
  - platform: locative
  - platform: bluetooth_tracker

climate:
  - platform: hitachi_ac
    name: AC
    min_temp: 18
    max_temp: 27
    target_temp: 23
    away: true
    aux: false
    fan_mode: Auto Low
    swing_mode: Auto
    ac_mode: heat
switch:
  - platform: mraa_gpio
    ports:
          6: 'chauffage'
